title: Akib Kamani 
author:
  name: Akib Kamani
description: > # this means to ignore newlines until "show_excerpts:"
  Hey there 👋I mostly do private research/project 🔭. Someday I'll write about it✨


show_excerpts: false # set to true to show excerpts on the homepage

paginate: 2
paginate_path: "/page/:num/"

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: akibkamani
    github:  akibkamani
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: akibkamani
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md

# Build settings
theme: minima

google_analytics: UA-125042999-11


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-archives


permalink: /:title:output_ext

jekyll-archives:
  enabled: all
  layouts:
    # year: archive/year
    # month: archive/month
    # day: archive/day
    tag: tag
    category: category
    author: author
  permalinks:
    # year: '/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    tag: '/:name/'
    category: '/:name/'
    author: '/:name/'